sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t kingo4luv/docker-react -f Dockerfile.dev .

# script:
#   - docker run kingo4luv/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-150164728911"
  bucket_path: "Docker-react"
  on:
    branch: master
